### ISSUE TITLE
[Request]请求修复从 Windows 重启进入 macOS 后扬声器没有声音的问题

### ISSUE THREAD

**Issue by topkie** [the-eric-kwok/HP-Pavilion-bc015tx-Hackintosh#1]
**Is your feature request related to a problem? Please describe.**
从 Windows 重启进入 macOS 后扬声器没有声音

**Describe alternatives you've considered**
卸载 Realtek 声卡驱动，切换为 Windows 自带的 HDA 驱动：https://www.jianshu.com/p/1584d5fbee09

**Additional context**
这个问题好像是 Windows 下的声卡驱动导致的。
搜到一个 HP cb073tx 的引导文件，把热重启替换成断电重启修复的：https://github.com/zty199/HP_Pavilion_15-cb073tx_Hackintosh/commit/af6ed1c925348d013b578b6729c7c77da401009b

**Comment by the-eric-kwok** [comment]
十分感谢，测试后将会merge

**Comment by the-eric-kwok** [comment]
将热重启改为断电重启感觉体验上会有影响？你在机器上有没有试过呢？会不会有硬盘掉电复位的噪音啊？
此外windows上使用默认声卡驱动好像也没有什么特别大的影响，是否有必要为此引入一个冷重启方式呢？

**Comment by the-eric-kwok** [comment]
噢突然意识到自己的post install那段忘记把声卡修复的文章加进去了😂
你搜到的那篇文章是我写的，我回头加一下文档，感谢！

**Comment by topkie** [comment]
> 将热重启改为断电重启感觉体验上会有影响？你在机器上有没有试过呢？会不会有硬盘掉电复位的噪音啊？ 此外windows上使用默认声卡驱动好像也没有什么特别大的影响，是否有必要为此引入一个冷重启方式呢？

掉电确实有噪音，所以提了个 issue 看看有没有更优雅的方法😂

**Comment by topkie** [comment]
卸载声卡驱动后已经正常👌
感谢回复！

**Comment by the-eric-kwok** [comment]
考虑到掉电噪音和对硬盘寿命影响的原因，暂不引入该补丁，文档已经更新，因此我将关闭此issue，如果有任何问题，欢迎重启issue或开一个新issue。
感谢支持❤️
